version: '2'
services:
  filegator:
    build: .
    image: filegator:latest
    restart: always
    ports:
      - "8081:8080"
    volumes:
      - repository:/var/www/filegator/repository
      - private:/var/www/filegator/private

volumes:
  repository:
  private:
