FROM php:8.3

RUN apt-get update > /dev/null
RUN apt-get install -y nodejs npm libldap2-dev libzip-dev

RUN docker-php-ext-configure ldap --with-libdir=lib/x86_64-linux-gnu/
RUN docker-php-ext-install zip ldap
RUN docker-php-ext-enable zip ldap

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

WORKDIR "/var/www/filegator/"

COPY . .
RUN composer install
RUN npm i
RUN cp -n configuration_sample.php configuration.php

CMD ["nohup", "bash", "-c", "npm run serve"]
