# Pin Composer source image by digest so the binary we COPY in is byte-fixed.
# The prior curl https://getcomposer.org/installer | php had no integrity check.
FROM composer:2@sha256:b09bccd91a78fe8a9ab4b33d707b862e8fe54fec17782e32683ad2a69c46867d AS composer-source

FROM php:8.3

RUN apt-get update > /dev/null
RUN apt-get install -y nodejs npm libldap2-dev libzip-dev

RUN docker-php-ext-configure ldap --with-libdir=lib/x86_64-linux-gnu/
RUN docker-php-ext-install zip ldap
RUN docker-php-ext-enable zip ldap

COPY --from=composer-source /usr/bin/composer /usr/local/bin/composer

WORKDIR "/var/www/filegator/"

COPY . .
RUN composer install
RUN npm i
RUN cp -n configuration_sample.php configuration.php

CMD ["nohup", "bash", "-c", "npm run serve"]
